trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'backend/Functions/Payment/Processing/Braintree/*'
      - 'backend/Functions/Payment/Common/Data/*'
      - 'backend/Integrations/BrainTreeClient/*'
      - 'backend/Integrations/ServiceBusClient/*'

variables:
  vmImageName: 'windows-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Functions/Payment/Processing/Braintree/Function'
  packageName: 'PaymentProcessingBraintree'

steps:
  - template: ../../../../../../DevOps/ci-dotNet8-AzureFunction-template.yml