trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'backend/Functions/Shopify/AppInstall/*'
      - 'backend/API/Seller/Common/Services/*'
      - 'backend/Common/Service/*'

variables:
  vmImageName: 'windows-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Functions/Shopify/AppInstall/Function'
  packageName: 'ShopifyAppInstall'

steps:
  - template: ../../../../../DevOps/ci-dotNet8-AzureFunction-template.yml