trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  ciPipeline: 'ci-functions-shopify-webhook-endpoints-main'
  functionAppName: 'pod-functions-shopify-webhook-endpoints-alpha'
  packageName: 'ShopifyWebhookEndpoints'
  project: 'POD'

resources:
  pipelines:
    - pipeline: ciFunctionsShopifyWebhookEndpointsMain
      source: 'ci-functions-shopify-webhook-endpoints-main'
      trigger: true

steps:
  - template: ../../../../../DevOps/cd-dotNet8-AzureFunction-template.yml