trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'backend/Functions/Shopify/WebhookEndpoints/*'
      - 'backend/Common/Database/*'
      - 'backend/Integrations/BlobClient/*'
      - 'backend/Integrations/ShopifyClient/*'
      - 'backend/Integrations/ServiceBusClient/*'

variables:
  vmImageName: 'windows-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Functions/Shopify/WebhookEndpoints/Function'
  packageName: 'ShopifyWebhookEndpoints'

steps:
  - template: ../../../../../DevOps/ci-dotNet8-AzureFunction-template.yml