trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  ciPipeline: 'ci-functions-shopify-app-uninstall-main'
  functionAppName: 'pod-functions-shopify-app-uninstall-alpha'
  packageName: 'ShopifyAppUninstall'
  project: 'POD'

resources:
  pipelines:
    - pipeline: ciFunctionsShopifyAppUninstallMain
      source: 'ci-functions-shopify-app-uninstall-main'
      trigger: true

steps:
  - template: ../../../../../DevOps/cd-dotNet8-AzureFunction-template.yml