trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'backend/Functions/Shopify/AppUninstall/*'
      - 'backend/Common/Database/*'
      - 'backend/Common/Service/*'

variables:
  vmImageName: 'windows-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Functions/Shopify/AppUninstall/Function'
  packageName: 'ShopifyAppUninstall'

steps:
  - template: ../../../../../DevOps/ci-dotNet8-AzureFunction-template.yml