trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  ciPipeline: 'ci-api-admin-model-main'
  functionAppName: 'pod-api-admin-model-alpha'
  packageName: 'AdminModel'
  project: 'POD'

resources:
  pipelines:
    - pipeline: ciApiAdminModelMain
      source: 'ci-api-admin-model-main'
      trigger: true

steps:
  - template: ../../../../../DevOps/cd-dotNet8-AzureFunction-template.yml