trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  ciPipeline: 'ci-functions-shopify-delete-product-main'
  functionAppName: 'pod-functions-shopify-delete-product-alpha'
  packageName: 'ShopifyDeleteProduct'
  project: 'POD'

resources:
  pipelines:
    - pipeline: ciFunctionsShopifyDeleteProductMain
      source: 'ci-functions-shopify-delete-product-main'
      trigger: true

steps:
  - template: ../../../../../DevOps/cd-dotNet8-AzureFunction-template.yml