trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'backend/Functions/Shopify/DeleteProduct/*'
      - 'backend/Common/Service/*'
      - 'backend/Common/Core/*'

variables:
  vmImageName: 'windows-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Functions/Shopify/DeleteProduct/Function'
  packageName: 'ShopifyDeleteProduct'

steps:
  - template: ../../../../../DevOps/ci-dotNet8-AzureFunction-template.yml