trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'backend/Functions/Shopify/OrderProcessing/*'
      - 'backend/Common/Database/*'
      - 'backend/Common/Service/*'
      - 'backend/Integrations/ServiceBusClient/*'

variables:
  vmImageName: 'windows-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Functions/Shopify/OrderProcessing/Function'
  packageName: 'ShopifyOrderProcessing'

steps:
  - template: ../../../../../DevOps/ci-dotNet8-AzureFunction-template.yml