trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  ciPipeline: 'ci-functions-shopify-call-executes-main'
  functionAppName: 'pod-functions-shopify-call-executes-alpha'
  packageName: 'ShopifyCallExecutes'
  project: 'POD'

resources:
  pipelines:
    - pipeline: ciFunctionsShopifyCallExecutesMain
      source: 'ci-functions-shopify-call-executes-main'
      trigger: true

steps:
  - template: ../../../../../DevOps/cd-dotNet8-AzureFunction-template.yml