trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'backend/Functions/Shopify/CallExecutes/*'
      - 'backend/Integrations/ShopifyClient/*'
      - 'backend/Integrations/ServiceBusClient/*'

variables:
  vmImageName: 'windows-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Functions/Shopify/CallExecutes/Function'
  packageName: 'ShopifyCallExecutes'

steps:
  - template: ../../../../../DevOps/ci-dotNet8-AzureFunction-template.yml