trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  ciPipeline: 'ci-api-user-identity-main'
  functionAppName: 'pod-api-user-identity-alpha'
  packageName: 'UserIdentity'
  project: 'POD'

resources:
  pipelines:
    - pipeline: ciApiUserIdentityMain
      source: 'ci-api-user-identity-main'
      trigger: true

steps:
  - template: ../../../../../DevOps/cd-dotNet8-AzureFunction-template.yml