trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'backend/API/User/Identity/*'
      - 'backend/Common/Service/*'
      - 'backend/Common/Database/*'
      - 'backend/Common/Core/*'

variables:
  vmImageName: 'windows-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/API/User/Identity/Function'
  packageName: 'UserIdentity'

steps:
  - template: ../../../../../DevOps/ci-dotNet8-AzureFunction-template.yml