trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'backend/Functions/Shopify/PublishProcessing/*'
      - 'backend/Common/Database/*'
      - 'backend/Common/Utils/*'
      - 'backend/Integrations/ServiceBusClient/*'

variables:
  vmImageName: 'windows-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Functions/Shopify/PublishProcessing/Function'
  packageName: 'ShopifyPublishProcessing'

steps:
  - template: ../../../../../DevOps/ci-dotNet8-AzureFunction-template.yml