trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'backend/API/Seller/Store/*'
      - 'backend/API/Seller/Common/Services/*'
      - 'backend/Common/Database/*'
      - 'backend/Common/Services/*'

variables:
  vmImageName: 'windows-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/API/Seller/Store/Function'
  packageName: 'SellerStore'

steps:
  - template: ../../../../../DevOps/ci-dotNet8-AzureFunction-template.yml